version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: initDockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - /etc/ssl/certs:/etc/ssl/certs
  certbot:
    image: certbot/certbot
    entrypoint: "certbot certonly --webroot -w /var/www/certbot --email endenwer@gmail.com -d api.balibike.app --rsa-key-size 4096 --agree-tos --force-renewal"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx
volumes:
  certbot-etc:
  certbot-www:

 
